# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('facebook_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('image_url', models.URLField()),
                ('locale', models.CharField(max_length=10)),
                ('timezone', models.SmallIntegerField(max_length=3)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
