# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.SmallIntegerField(),
        ),
    ]
