# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 11:55
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0002_auto_20170512_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
