# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0003_auto_20170513_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.User'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('facebook_id', 'team_name')]),
        ),
    ]
