# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0004_auto_20170515_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='context',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
