# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0005_auto_20170515_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(default='')),
                ('time_since_added', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='context',
            field=models.SmallIntegerField(default=1),
        ),
    ]
