# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0007_footballteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballTeam'),
        ),
    ]
