# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0008_auto_20171224_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='source',
            field=models.CharField(default='footyroom', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='team_1',
            field=models.ForeignKey(db_column='team_1', default='barcelona', on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='fb_highlights.FootballTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='team_2',
            field=models.ForeignKey(db_column='team_2', default='barcelona', on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='fb_highlights.FootballTeam'),
            preserve_default=False,
        ),
    ]
