# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0009_auto_20171225_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
