# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0010_latesthighlight_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latesthighlight',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='latesthighlight',
            name='team_2',
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='team1',
            field=models.ForeignKey(db_column='team1', default='barcelona', on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='fb_highlights.FootballTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='team2',
            field=models.ForeignKey(db_column='team2', default='barcelona', on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='fb_highlights.FootballTeam'),
            preserve_default=False,
        ),
    ]
