# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0013_auto_20171229_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFootballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newfootballteam',
            unique_together=set([('name', 'source')]),
        ),
    ]
