# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0014_auto_20180111_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='highlights_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
