# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0016_remove_latesthighlight_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.SmallIntegerField()),
                ('score2', models.SmallIntegerField()),
                ('link', models.TextField()),
                ('time', models.CharField(max_length=120)),
                ('team1', models.ForeignKey(db_column='team1', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_stat_team1', to='fb_highlights.FootballTeam')),
                ('team2', models.ForeignKey(db_column='team2', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_stat_team2', to='fb_highlights.FootballTeam')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='highlightstat',
            unique_together=set([('user', 'time')]),
        ),
    ]
