# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0017_auto_20180124_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightNotificationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.SmallIntegerField()),
                ('score2', models.SmallIntegerField()),
                ('match_time', models.CharField(max_length=120)),
                ('send_time', models.CharField(max_length=120)),
                ('open_time', models.CharField(default='', max_length=120)),
                ('opened', models.BooleanField(default=False)),
                ('team1', models.ForeignKey(db_column='team1', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_notification_stat_team1', to='fb_highlights.FootballTeam')),
                ('team2', models.ForeignKey(db_column='team2', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_notification_stat_team2', to='fb_highlights.FootballTeam')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='highlightnotificationstat',
            unique_together=set([('user', 'send_time')]),
        ),
    ]
