# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0018_auto_20180201_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightnotificationstat',
            name='open_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightnotificationstat',
            name='send_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightstat',
            name='time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
