# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0020_auto_20180219_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlightnotificationstat',
            old_name='open_time_2',
            new_name='open_time',
        ),
        migrations.RenameField(
            model_name='highlightnotificationstat',
            old_name='send_time_2',
            new_name='send_time',
        ),
        migrations.AlterUniqueTogether(
            name='highlightnotificationstat',
            unique_together=set([('user', 'send_time')]),
        ),
    ]
