# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0022_auto_20180220_0000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlightstat',
            unique_together=set([('user', 'time_2')]),
        ),
        migrations.RemoveField(
            model_name='highlightstat',
            name='time',
        ),
    ]
