# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0023_auto_20180220_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlightstat',
            old_name='time_2',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='highlightstat',
            unique_together=set([('user', 'time')]),
        ),
    ]
