# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0028_latesthighlight_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballCompetition',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewFootballCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.ForeignKey(db_column='competition_name', on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballCompetition')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='RegistrationTeam',
        ),
        migrations.AlterUniqueTogether(
            name='newfootballcompetition',
            unique_together=set([('name', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='registrationcompetition',
            unique_together=set([('user', 'competition_name')]),
        ),
    ]
