# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0031_auto_20180414_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
