# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-25 18:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0032_latesthighlight_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='goal_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
