# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0034_user_see_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latesthighlight',
            old_name='priority',
            new_name='priority_short',
        ),
        migrations.AddField(
            model_name='latesthighlight',
            name='priority_extended',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
