# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0035_auto_20180507_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightstat',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
