# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0037_highlightstat_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightstat',
            name='video_duration',
            field=models.IntegerField(default=-2),
        ),
    ]
