# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0040_latesthighlight_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='type',
            field=models.CharField(default='normal', max_length=80),
        ),
    ]
