# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0043_newfootballregistration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappingStatus',
            fields=[
                ('site_name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('ok', models.BooleanField(default=True)),
            ],
        ),
    ]
