# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0044_scrappingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperApiKeys',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('last_invalid_try', models.DateTimeField()),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
