# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-05 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0045_scraperapikeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScraperApiKeys',
            new_name='ScraperApiKey',
        ),
    ]
