# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-05 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0046_auto_20180805_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperapikey',
            name='last_invalid_try',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 18, 37, 37, 734745)),
        ),
        migrations.AlterField(
            model_name='scraperapikey',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
