# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-20 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0049_auto_20180820_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperapikey',
            name='last_invalid_try',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
