# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0050_auto_20180820_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latesthighlight',
            name='time_since_added',
            field=models.DateTimeField(),
        ),
    ]
