# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-12 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0051_auto_20181012_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='match_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 8, 9, 19, 341551)),
            preserve_default=False,
        ),
    ]
