# Generated by Django 2.1.2 on 2018-10-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0052_latesthighlight_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesthighlight',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
