# Generated by Django 2.1.2 on 2018-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0053_latesthighlight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latesthighlight',
            name='id',
            field=models.PositiveIntegerField(),
        ),
    ]
