# Generated by Django 2.1.2 on 2018-11-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0054_auto_20181025_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedForCompetitionHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballCompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballTeam')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deniedforcompetitionhighlight',
            unique_together={('team', 'competition')},
        ),
    ]
