# Generated by Django 2.2.1 on 2019-05-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0059_newfootballregistration_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newfootballregistration',
            unique_together=set(),
        ),
    ]
