# Generated by Django 2.2.1 on 2019-05-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0060_auto_20190508_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_column='team_name_mapping', max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballTeam')),
            ],
            options={
                'unique_together': {('team_name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='FootballCompetitionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(db_column='competition_name_mapping', max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballCompetition')),
            ],
            options={
                'unique_together': {('competition_name', 'competition')},
            },
        ),
    ]
