# Generated by Django 2.2.1 on 2019-09-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0062_highlightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockednotification',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_highlights.FootballTeam'),
        ),
    ]
