# Generated by Django 2.2.1 on 2019-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_highlights', '0063_auto_20190908_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperapikey',
            name='mail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scraperapikey',
            name='password',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
