STREAMABLE = 'streamable.com'
DAILYMOTION = 'dailymotion.com'
OK_RU = 'ok.ru'
FOOYTROOM = 'footyroom.com'
YOUTUBE = 'youtube.com'
RUTUBE = 'rutube.ru'
MLSOCCER = 'mlssoccer.com'

# Similar format, different hosting platform
CONTENT_VENTURES = 'content-ventures.com'
MATCHAT_ONLINE = 'matchat.online'
VIDEO_STREAMLET = 'videostreamlet.net'
VEUCLIPS = 'veuclips.com'
VIUCLIPS = 'viuclips.net'
VIDSTREAM = 'vidstreamup.com'
TOCLIPIT = 'toclipit.com'
CLIPVENTURES = 'clipventures.com'
TO_STREAMIT = 'tostreamit.com'
UPCLIPS = 'upclips.online'
VIDSFORU = 'vidsforu.com'
VSTREAMEU = 'vstreameu.live'