STREAMABLE = 'streamable.com'
DAILYMOTION = 'dailymotion.com'
OK_RU = 'ok.ru'
MATCHAT_ONLINE = 'matchat.online'
VIDEO_STREAMLET = 'videostreamlet.net'
CONTENT_VENTURES = 'content-ventures.com'
FOOYTROOM = 'footyroom.com'
YOUTUBE = 'youtube.com'